version: "3.8"

services:
    php-env:
      image: phpmyadmin/phpmyadmin:latest
      volumes: 
      - "./:/var/www/html"
      ports:
      - 8000:80
      depends_on:
      - mysql_db

    mysql_db:
      container_name: mysql_db
      image: mysql:latest
      restart: always
      environment:
      - MYSQL_DATABASE=azhar
      - MYSQL_USER=database
      - MYSQL_PASSWORD=azhar
        
      volumes:
      - "./database:/docker-entrypoint-initdb.d"

      

    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - 8082:80
      environment:
        - PMA_HOST=mysql_db
        - PMA_PORT=3306